### ISSUE TITLE
Change colors to standard Apple colors

### ISSUE THREAD

**Issue by famer** [famer/device.css#4]
Rename color classes to standard Apple "space gray" and "silver" instead of "white" and "black".
UPDATE: http://store.apple.com/us/buy-iphone/iphone6

**Comment by waterplea** [comment]
Does anybody besides you know they are called like that? :-)
23 Май 2015 г. 22:09 пользователь "Timur Tatarshaov" <
notifications@github.com> написал:

**Comment by famer** [comment]
@waterplea updated
